# @package _group_
_target_: models.criterion.SetCriterion
train_is_true: ${general.train_mode}
num_classes: ${general.num_targets}
eos_coef: 0.1
losses:
  - "labels"
  - "masks"
num_points: ${matcher.num_points}
oversample_ratio: 3.0
importance_sample_ratio: 0.75
class_weights: -1
num_querries: ${model.num_queries}
store_path: ${general.store_path}
clustering_start_iter: ${general.clustering_start_iter}
clustering_update_mu_iter: ${general.clustering_update_mu_iter}
enable_baseline_clustering: ${general.enable_baseline_clustering}
clustering_momentum: ${general.clustering_momentum}
store_size: ${general.store_size}
